// src/main.rs
// Android Messages — cross-platform SMS app built with Rust + Slint.
//
// Architecture: MVU-inspired unidirectional data flow.
//   UI layer (Slint) → Callbacks → AppController → DB/Crypto → UI state update
//
// The UI runs on the main thread (required by most windowing systems).
// Heavy work (DB queries, crypto) runs on a tokio thread pool, then posts
// results back to the Slint event loop via `slint::invoke_from_event_loop`.

// ── No unwrap() in production paths (enforced by clippy::unwrap_used below) ──
#![warn(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
#![allow(clippy::module_inception)]

mod db;
mod crypto;
mod models;
mod services;
mod utils;

use std::sync::Arc;
use anyhow::Result;
use log::{error, info};

// The `slint::include_modules!()` macro expands the generated code from
// build.rs's slint_build::compile() call.  It creates Rust structs for every
// component and struct declared in our .slint files.
slint::include_modules!();

use services::app_controller::AppController;

fn main() -> Result<()> {
    // ── Logging ───────────────────────────────────────────────────────────
    // RUST_LOG=debug cargo run   → verbose output
    // RUST_LOG=info  cargo run   → normal output
    env_logger::Builder::from_env(
        env_logger::Env::default().default_filter_or("info"),
    )
    .init();

    info!("Android Messages v{} starting…", env!("CARGO_PKG_VERSION"));

    // ── Tokio runtime (multi-threaded, capped at 4 workers for mobile) ────
    // We build it manually so we control thread count — important for keeping
    // memory footprint low on resource-constrained Android devices.
    let rt = tokio::runtime::Builder::new_multi_thread()
        .worker_threads(4)
        .enable_all()
        .build()
        .map_err(|e| anyhow::anyhow!("Failed to create Tokio runtime: {e}"))?;

    // ── Create the Slint window ───────────────────────────────────────────
    // AppWindow is generated by slint::include_modules!() from app.slint.
    let window = AppWindow::new()
        .map_err(|e| anyhow::anyhow!("Slint window creation failed: {e}"))?;

    // ── Database initialisation ───────────────────────────────────────────
    // We open the database on the main thread before handing off to async,
    // so startup errors surface immediately.
    let data_dir = utils::paths::app_data_dir()?;
    std::fs::create_dir_all(&data_dir)
        .map_err(|e| anyhow::anyhow!("Cannot create data directory: {e}"))?;

    let db_path = data_dir.join("messages.db");
    let db = Arc::new(
        db::Database::open(&db_path)
            .map_err(|e| anyhow::anyhow!("Database open failed: {e}"))?,
    );

    info!("Database opened at {}", db_path.display());

    // ── Controller ────────────────────────────────────────────────────────
    // AppController holds shared state and wires callbacks to Slint signals.
    let controller = Arc::new(AppController::new(
        window.as_weak(),
        db.clone(),
        rt.handle().clone(),
    ));

    // ── Wire all UI callbacks ─────────────────────────────────────────────
    services::wiring::wire_callbacks(&window, controller.clone());

    // ── Optional demo data ────────────────────────────────────────────────
    if std::env::args().any(|a| a == "--demo") {
        info!("--demo flag: seeding demo data…");
        if let Err(e) = utils::seed::seed_demo_data(&db) {
            error!("Demo seed failed: {e}");
        }
    }

    // ── Load initial data ─────────────────────────────────────────────────
    {
        let ctrl = controller.clone();
        rt.spawn(async move {
            if let Err(e) = ctrl.load_conversations().await {
                error!("Initial load failed: {e}");
            }
        });
    }

    // ── Enter the Slint event loop (blocks until window is closed) ────────
    // All UI mutations MUST happen on this thread or via invoke_from_event_loop.
    window.run()
        .map_err(|e| anyhow::anyhow!("Slint event loop error: {e}"))?;

    info!("Application exiting cleanly.");
    Ok(())
}
