// Types AppWindow, ContactEntry, GroupEntry are generated by Slint
// and re-exported from the crate root (lib.rs via include_modules!())
use crate::{AppWindow, ContactEntry, GroupEntry};

// src/app.rs
// Shared application startup logic used by both:
//   - src/main.rs (desktop: fn main)
//   - android/src/lib.rs (Android: android_main)
//
// This module is the heart of the bridge between Slint UI callbacks and Rust backend.

use std::rc::Rc;
use std::cell::RefCell;

use anyhow::Result;
use log::{error, info};

use crate::contacts::ContactManager;
use crate::models::{Contact, SortKey};


pub fn run_app() -> Result<()> {
    let data_dir = crate::storage::app_data_dir();
    info!("Data directory: {}", data_dir.display());

    let manager = Rc::new(RefCell::new(
        ContactManager::new(data_dir)?
    ));

    let window = AppWindow::new()?;

    // Initial data load
    {
        let mgr = manager.borrow();
        refresh_ui(&window, &mgr);
    }

    // ── search_contacts callback ───────────────────────────────────────────────
    {
        let mgr = manager.clone();
        window.on_search_contacts(move |query: slint::SharedString| {
            let mgr = mgr.borrow();
            let results = mgr.search(query.as_str());
            slint::VecModel::from_slice(&results.iter().map(contact_to_slint).collect::<Vec<_>>())
        });
    }

    // ── save_contact callback ─────────────────────────────────────────────────
    {
        let mgr = manager.clone();
        let window_weak = window.as_weak();
        window.on_save_contact(move |entry: ContactEntry| {
            let mut mgr = mgr.borrow_mut();
            match mgr.upsert(slint_to_contact(&entry)) {
                Ok(_) => {
                    if let Some(w) = window_weak.upgrade() { refresh_ui(&w, &mgr); }
                    true
                }
                Err(e) => { error!("Save contact: {e}"); false }
            }
        });
    }

    // ── delete_contact callback ───────────────────────────────────────────────
    {
        let mgr = manager.clone();
        let window_weak = window.as_weak();
        window.on_delete_contact(move |id: slint::SharedString| {
            let mut mgr = mgr.borrow_mut();
            match mgr.delete(id.as_str()) {
                Ok(_) => {
                    if let Some(w) = window_weak.upgrade() { refresh_ui(&w, &mgr); }
                    true
                }
                Err(e) => { error!("Delete contact: {e}"); false }
            }
        });
    }

    // ── toggle_favorite callback ──────────────────────────────────────────────
    {
        let mgr = manager.clone();
        let window_weak = window.as_weak();
        window.on_toggle_favorite(move |id: slint::SharedString| {
            let mut mgr = mgr.borrow_mut();
            match mgr.toggle_favorite(id.as_str()) {
                Ok(v) => {
                    if let Some(w) = window_weak.upgrade() { refresh_ui(&w, &mgr); }
                    v
                }
                Err(e) => { error!("Toggle fav: {e}"); false }
            }
        });
    }

    // ── request_sort callback ─────────────────────────────────────────────────
    {
        let mgr = manager.clone();
        let window_weak = window.as_weak();
        window.on_request_sort(move |key: slint::SharedString| {
            let sort = match key.as_str() {
                "last"  => SortKey::LastName,
                "phone" => SortKey::Phone,
                _       => SortKey::FirstName,
            };
            let mut mgr = mgr.borrow_mut();
            mgr.set_sort(sort);
            if let Some(w) = window_weak.upgrade() { refresh_ui(&w, &mgr); }
        });
    }

    // ── refresh_contacts callback ─────────────────────────────────────────────
    {
        let mgr = manager.clone();
        let window_weak = window.as_weak();
        window.on_refresh_contacts(move || {
            let mgr = mgr.borrow();
            if let Some(w) = window_weak.upgrade() { refresh_ui(&w, &mgr); }
        });
    }

    // ── import_contacts callback ──────────────────────────────────────────────
    {
        let mgr = manager.clone();
        let window_weak = window.as_weak();
        window.on_import_contacts(move |_path: slint::SharedString| -> i32 {
            #[cfg(not(target_os = "android"))]
            {
                let file = rfd::FileDialog::new()
                    .add_filter("Contacts", &["vcf", "csv", "json"])
                    .set_title("Import Contacts")
                    .pick_file();

                if let Some(path) = file {
                    let mut mgr = mgr.borrow_mut();
                    match mgr.import_file(&path) {
                        Ok(count) => {
                            if let Some(w) = window_weak.upgrade() {
                                refresh_ui(&w, &mgr);
                                show_toast(&w, &format!("Imported {count} contacts"), false);
                            }
                            count as i32
                        }
                        Err(e) => {
                            error!("Import: {e}");
                            if let Some(w) = window_weak.upgrade() {
                                show_toast(&w, &format!("Import failed: {e}"), true);
                            }
                            0
                        }
                    }
                } else { 0 }
            }
            #[cfg(target_os = "android")]
            { 0 } // Android import uses system intent
        });
    }

    // ── export_contacts callback ──────────────────────────────────────────────
    {
        let mgr = manager.clone();
        let window_weak = window.as_weak();
        window.on_export_contacts(move |_path: slint::SharedString| -> bool {
            #[cfg(not(target_os = "android"))]
            {
                let file = rfd::FileDialog::new()
                    .add_filter("vCard", &["vcf"])
                    .set_title("Export Contacts")
                    .set_file_name("contacts.vcf")
                    .save_file();

                if let Some(path) = file {
                    let mgr = mgr.borrow();
                    match mgr.export_vcf(&path) {
                        Ok(count) => {
                            if let Some(w) = window_weak.upgrade() {
                                show_toast(&w, &format!("Exported {count} contacts"), false);
                            }
                            true
                        }
                        Err(e) => {
                            error!("Export: {e}");
                            if let Some(w) = window_weak.upgrade() {
                                show_toast(&w, &format!("Export failed: {e}"), true);
                            }
                            false
                        }
                    }
                } else { false }
            }
            #[cfg(target_os = "android")]
            false
        });
    }

    // ── get_groups callback ───────────────────────────────────────────────────
    {
        let mgr = manager.clone();
        window.on_get_groups(move || {
            let mgr = mgr.borrow();
            slint::VecModel::from_slice(
                &mgr.groups().iter().map(group_to_slint).collect::<Vec<_>>()
            )
        });
    }

    // ── save_group callback ───────────────────────────────────────────────────
    {
        let mgr = manager.clone();
        let window_weak = window.as_weak();
        window.on_save_group(move |entry: GroupEntry| {
            let mut mgr = mgr.borrow_mut();
            let group = crate::models::Group {
                id: if entry.id.is_empty() {
                    uuid::Uuid::new_v4().to_string()
                } else {
                    entry.id.to_string()
                },
                name: entry.name.to_string(),
                count: entry.count as usize,
                color: 0x1565C0,
            };
            match mgr.upsert_group(group) {
                Ok(_) => {
                    if let Some(w) = window_weak.upgrade() { refresh_ui(&w, &mgr); }
                    true
                }
                Err(e) => { error!("Save group: {e}"); false }
            }
        });
    }

    // ── delete_group callback ─────────────────────────────────────────────────
    {
        let mgr = manager.clone();
        let window_weak = window.as_weak();
        window.on_delete_group(move |id: slint::SharedString| {
            let mut mgr = mgr.borrow_mut();
            match mgr.delete_group(id.as_str()) {
                Ok(_) => {
                    if let Some(w) = window_weak.upgrade() { refresh_ui(&w, &mgr); }
                    true
                }
                Err(e) => { error!("Delete group: {e}"); false }
            }
        });
    }

    // ── show_toast callback ───────────────────────────────────────────────────
    {
        let window_weak = window.as_weak();
        window.on_show_toast(move |msg: slint::SharedString, is_error: bool| {
            if let Some(w) = window_weak.upgrade() {
                show_toast(&w, msg.as_str(), is_error);
            }
        });
    }

    window.run()?;
    info!("App exiting normally");
    Ok(())
}

// ── UI Helpers ────────────────────────────────────────────────────────────────

fn refresh_ui(window: &AppWindow, mgr: &ContactManager) {
    let all = mgr.all_sorted();
    let favs: Vec<_> = all.iter().filter(|c| c.is_favorite).collect();

    window.set_contacts(slint::VecModel::from_slice(
        &all.iter().map(contact_to_slint).collect::<Vec<_>>(),
    ));
    window.set_filtered_contacts(slint::VecModel::from_slice(
        &all.iter().map(contact_to_slint).collect::<Vec<_>>(),
    ));
    window.set_favorite_contacts(slint::VecModel::from_slice(
        &favs.iter().map(|c| contact_to_slint(c)).collect::<Vec<_>>(),
    ));
    window.set_groups(slint::VecModel::from_slice(
        &mgr.groups().iter().map(group_to_slint).collect::<Vec<_>>(),
    ));
}

fn show_toast(window: &AppWindow, msg: &str, is_error: bool) {
    window.set_toast_message(msg.into());
    window.set_toast_is_error(is_error);
    window.set_toast_visible(true);
    let w = window.as_weak();
    slint::Timer::single_shot(std::time::Duration::from_secs(3), move || {
        if let Some(win) = w.upgrade() { win.set_toast_visible(false); }
    });
}

// ── Type Converters ───────────────────────────────────────────────────────────

pub fn contact_to_slint(c: &Contact) -> ContactEntry {
    let (r, g, b) = split_rgb(c.avatar_color);
    ContactEntry {
        id: c.id.clone().into(),
        first_name: c.first_name.clone().into(),
        last_name: c.last_name.clone().into(),
        phone_primary: c.phone_primary.clone().into(),
        phone_secondary: c.phone_secondary.clone().into(),
        email: c.email.clone().into(),
        organization: c.organization.clone().into(),
        job_title: c.job_title.clone().into(),
        website: c.website.clone().into(),
        notes: c.notes.clone().into(),
        group: c.group.clone().into(),
        is_favorite: c.is_favorite,
        avatar_color: slint::Color::from_rgb_u8(r, g, b),
        avatar_letter: c.avatar_letter().into(),
        created_at: c.created_at.clone().into(),
        updated_at: c.updated_at.clone().into(),
    }
}

pub fn slint_to_contact(e: &ContactEntry) -> Contact {
    Contact {
        id: if e.id.is_empty() {
            uuid::Uuid::new_v4().to_string()
        } else {
            e.id.to_string()
        },
        first_name: e.first_name.to_string(),
        last_name: e.last_name.to_string(),
        phone_primary: e.phone_primary.to_string(),
        phone_secondary: e.phone_secondary.to_string(),
        email: e.email.to_string(),
        organization: e.organization.to_string(),
        job_title: e.job_title.to_string(),
        website: e.website.to_string(),
        notes: e.notes.to_string(),
        group: e.group.to_string(),
        is_favorite: e.is_favorite,
        avatar_color: merge_rgb(
            e.avatar_color.red(),
            e.avatar_color.green(),
            e.avatar_color.blue(),
        ),
        created_at: e.created_at.to_string(),
        updated_at: String::new(),
    }
}

fn group_to_slint(g: &crate::models::Group) -> GroupEntry {
    let (r, gb, b) = split_rgb(g.color);
    GroupEntry {
        id: g.id.clone().into(),
        name: g.name.clone().into(),
        count: g.count as i32,
        color: slint::Color::from_rgb_u8(r, gb, b),
    }
}

#[inline] fn split_rgb(c: u32) -> (u8, u8, u8) {
    (((c >> 16) & 0xFF) as u8, ((c >> 8) & 0xFF) as u8, (c & 0xFF) as u8)
}
#[inline] fn merge_rgb(r: u8, g: u8, b: u8) -> u32 {
    ((r as u32) << 16) | ((g as u32) << 8) | b as u32
}
